### ISSUE TITLE
difference between autoSync & autoSave?

### ISSUE THREAD

**Issue by deadcoder0904** [lukesmurray/react-query-autosync#2]
also, the link on the blog → https://lukesmurray.com/blog/react-query-auto-sync-hook on `code for this hook` points to 404

i can't understand the need for 2 files: `autoSync` & `autoSave`

i want to achieve the same thing so thanks for the blog post :)

**Comment by deadcoder0904** [comment]
i hadn't read the readme but it answered this question:

> The difference between the two is the save hook is unidirectional and only saves a local value to the server when the local value changes. This can be useful for automatically saving things like logs, user analytivcs, or error reports. The sync hook is useful for things like documents where you don't want the user to have to press a save button to keep their changes.

although naming could be improved. i was wondering if this supports autogenerated queries & mutations from `graphql-codegen`?

**Comment by lukesmurray** [comment]
Thanks for the issue. I fixed the link. If you have any better naming suggestions I would be happy to consider them. I don't want to break backward compatibility but  I could add 1-2 additional exports. Integration is definitely possible with graphql codegen. If I were going to take that approach I would have graphql codegen generate plain API calls (e.g. using fetch/axios). I would then pass those API calls as the `queryFn` or `mutationFn` to this hook.

**Comment by deadcoder0904** [comment]
Yes, I managed to make `graphql-codegen` work last night only by reading the example code :)

I think you can link to the `Demo` file from the `readme` instead of linking to the whole `src` code to find the usage of `useReactAutoSync` hook directly 👍
